import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["BIGMANCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["BIGMANCODE_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("BIGMANCODE_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  BIGMANCODE_AUTO_HEAP_SNAPSHOT: truthy("BIGMANCODE_AUTO_HEAP_SNAPSHOT"),
  BIGMANCODE_GIT_BASH_PATH: process.env["BIGMANCODE_GIT_BASH_PATH"],
  BIGMANCODE_CONFIG: process.env["BIGMANCODE_CONFIG"],
  BIGMANCODE_CONFIG_CONTENT: process.env["BIGMANCODE_CONFIG_CONTENT"],
  BIGMANCODE_DISABLE_AUTOUPDATE: truthy("BIGMANCODE_DISABLE_AUTOUPDATE"),
  BIGMANCODE_ALWAYS_NOTIFY_UPDATE: truthy("BIGMANCODE_ALWAYS_NOTIFY_UPDATE"),
  BIGMANCODE_DISABLE_PRUNE: truthy("BIGMANCODE_DISABLE_PRUNE"),
  BIGMANCODE_DISABLE_TERMINAL_TITLE: truthy("BIGMANCODE_DISABLE_TERMINAL_TITLE"),
  BIGMANCODE_SHOW_TTFD: truthy("BIGMANCODE_SHOW_TTFD"),
  BIGMANCODE_DISABLE_AUTOCOMPACT: truthy("BIGMANCODE_DISABLE_AUTOCOMPACT"),
  BIGMANCODE_DISABLE_MODELS_FETCH: truthy("BIGMANCODE_DISABLE_MODELS_FETCH"),
  BIGMANCODE_DISABLE_MOUSE: truthy("BIGMANCODE_DISABLE_MOUSE"),
  BIGMANCODE_FAKE_VCS: process.env["BIGMANCODE_FAKE_VCS"],
  BIGMANCODE_SERVER_PASSWORD: process.env["BIGMANCODE_SERVER_PASSWORD"],
  BIGMANCODE_SERVER_USERNAME: process.env["BIGMANCODE_SERVER_USERNAME"],
  BIGMANCODE_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("BIGMANCODE_DISABLE_FFF"),

  // Experimental
  BIGMANCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("BIGMANCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  BIGMANCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("BIGMANCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  BIGMANCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("BIGMANCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  BIGMANCODE_MODELS_URL: process.env["BIGMANCODE_MODELS_URL"],
  BIGMANCODE_MODELS_PATH: process.env["BIGMANCODE_MODELS_PATH"],
  BIGMANCODE_DB: process.env["BIGMANCODE_DB"],

  BIGMANCODE_WORKSPACE_ID: process.env["BIGMANCODE_WORKSPACE_ID"],
  BIGMANCODE_EXPERIMENTAL_WORKSPACES: enabledByExperimental("BIGMANCODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get BIGMANCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("BIGMANCODE_DISABLE_PROJECT_CONFIG")
  },
  get BIGMANCODE_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("BIGMANCODE_EXPERIMENTAL_REFERENCES")
  },
  get BIGMANCODE_TUI_CONFIG() {
    return process.env["BIGMANCODE_TUI_CONFIG"]
  },
  get BIGMANCODE_CONFIG_DIR() {
    return process.env["BIGMANCODE_CONFIG_DIR"]
  },
  get BIGMANCODE_PURE() {
    return truthy("BIGMANCODE_PURE")
  },
  get BIGMANCODE_PERMISSION() {
    return process.env["BIGMANCODE_PERMISSION"]
  },
  get BIGMANCODE_PLUGIN_META_FILE() {
    return process.env["BIGMANCODE_PLUGIN_META_FILE"]
  },
  get BIGMANCODE_CLIENT() {
    return process.env["BIGMANCODE_CLIENT"] ?? "cli"
  },
}
